DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
    SHUFFLE: True
  TEST:
    BATCH_SIZE: 256
    SHUFFLE: False
  VAL:
    BATCH_SIZE: 256
    SHUFFLE: False
  NUM_WORKERS: 3

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

TEST:
  Analyze_Result_Path: './analysis_results_test/'
  FINAL_MODEL: "last_val"
  PER_CLASS_RESULT: True

MODEL:
  BACKBONE:
    NAME: "RN101"
  PSEUDO_LABEL_MODELS: ['RN101']
  